// <auto-generated />
using System;
using ChopNShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChopNShop.Migrations
{
    [DbContext(typeof(KitchenContext))]
    [Migration("20260712155948_AddStepsAndPrepTime")]
    partial class AddStepsAndPrepTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ChopNShop.Models.Chef", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Chef", (string)null);
                });

            modelBuilder.Entity("ChopNShop.Models.Inclusion", b =>
                {
                    b.Property<int>("InclusionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("InclusionID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Inclusion", (string)null);
                });

            modelBuilder.Entity("ChopNShop.Models.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("ChopNShop.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChefID")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("PrepTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepsRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeID");

                    b.HasIndex("ChefID");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("ChopNShop.Models.Inclusion", b =>
                {
                    b.HasOne("ChopNShop.Models.Ingredient", "Ingredient")
                        .WithMany("Inclusions")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChopNShop.Models.Recipe", "Recipe")
                        .WithMany("Inclusions")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChopNShop.Models.Recipe", b =>
                {
                    b.HasOne("ChopNShop.Models.Chef", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ChefID");
                });

            modelBuilder.Entity("ChopNShop.Models.Chef", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("ChopNShop.Models.Ingredient", b =>
                {
                    b.Navigation("Inclusions");
                });

            modelBuilder.Entity("ChopNShop.Models.Recipe", b =>
                {
                    b.Navigation("Inclusions");
                });
#pragma warning restore 612, 618
        }
    }
}
